// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_wSehCYO1ts0NBry8aUAvsRH6GHOUhR8',
    appId: '1:105215017114:web:43237870335992e0d31f23',
    messagingSenderId: '105215017114',
    projectId: 'chatapp-78099',
    authDomain: 'chatapp-78099.firebaseapp.com',
    storageBucket: 'chatapp-78099.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGj4Nb-L9beEEXRropaOsDNErVRKrDS9Q',
    appId: '1:105215017114:android:1da1fd91e16de588d31f23',
    messagingSenderId: '105215017114',
    projectId: 'chatapp-78099',
    storageBucket: 'chatapp-78099.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-72xf_g1ZtSaY6c9zxqd808qRlg6PD9s',
    appId: '1:105215017114:ios:37bf57238f49fd0fd31f23',
    messagingSenderId: '105215017114',
    projectId: 'chatapp-78099',
    storageBucket: 'chatapp-78099.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-72xf_g1ZtSaY6c9zxqd808qRlg6PD9s',
    appId: '1:105215017114:ios:37bf57238f49fd0fd31f23',
    messagingSenderId: '105215017114',
    projectId: 'chatapp-78099',
    storageBucket: 'chatapp-78099.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_wSehCYO1ts0NBry8aUAvsRH6GHOUhR8',
    appId: '1:105215017114:web:713ebaf9a72d359dd31f23',
    messagingSenderId: '105215017114',
    projectId: 'chatapp-78099',
    authDomain: 'chatapp-78099.firebaseapp.com',
    storageBucket: 'chatapp-78099.appspot.com',
  );
}
