name: money_mate
description: "Personal Expense Treacker"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  fl_chart: ^0.68.0
  intl: ^0.19.0
  firebase_core: ^3.2.0
  cloud_firestore: ^5.1.0
  firebase_auth: ^5.1.2
  fluttertoast: ^8.2.6
  share_plus: ^10.0.0
  syncfusion_flutter_charts: ^28.1.35


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.3.0

flutter:
  uses-material-design: true

  assets:
    - icons/
    - images/
    - assets/
  fonts:
    - family: Playwrite
      fonts:
        - asset: fonts/PlaywriteDEGrund.ttf
    - family: Newfont
      fonts:
        - asset: fonts/SpaceGrotesk-VariableFont_wght.ttf


