// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsnxjAtH04Im5gNZZqJ2mJEo79dUOUYIk',
    appId: '1:980956486577:web:c36c71d6e2d811da02bb90',
    messagingSenderId: '980956486577',
    projectId: 'health-tracker-1a898',
    authDomain: 'health-tracker-1a898.firebaseapp.com',
    storageBucket: 'health-tracker-1a898.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxr6-8qVcYj1UDo9_M-23snBjco06kaRU',
    appId: '1:980956486577:android:7298016a678d7bce02bb90',
    messagingSenderId: '980956486577',
    projectId: 'health-tracker-1a898',
    storageBucket: 'health-tracker-1a898.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoBYd1oiPKaABROnoCzz6FGDs-WDx_YtQ',
    appId: '1:980956486577:ios:8d3cfc67f393cfcc02bb90',
    messagingSenderId: '980956486577',
    projectId: 'health-tracker-1a898',
    storageBucket: 'health-tracker-1a898.appspot.com',
    iosBundleId: 'com.example.healthTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoBYd1oiPKaABROnoCzz6FGDs-WDx_YtQ',
    appId: '1:980956486577:ios:8d3cfc67f393cfcc02bb90',
    messagingSenderId: '980956486577',
    projectId: 'health-tracker-1a898',
    storageBucket: 'health-tracker-1a898.appspot.com',
    iosBundleId: 'com.example.healthTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsnxjAtH04Im5gNZZqJ2mJEo79dUOUYIk',
    appId: '1:980956486577:web:df7276d5954b7d1c02bb90',
    messagingSenderId: '980956486577',
    projectId: 'health-tracker-1a898',
    authDomain: 'health-tracker-1a898.firebaseapp.com',
    storageBucket: 'health-tracker-1a898.appspot.com',
  );
}
